# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2lF5Uqg0AHoUHmtf-dkVHebt3cgODkU
"""

# 📌 Installation der benötigten Pakete (nur für lokale Ausführung)
try:
    import streamlit as st
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import ccxt
    import plotly.express as px
    from ib_insync import *
    import nest_asyncio
    from web3 import Web3
    from sklearn.preprocessing import MinMaxScaler
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import LSTM, Dense, Dropout
    import os
except ImportError:
    os.system("pip install streamlit yfinance pandas numpy scikit-learn matplotlib tensorflow keras requests ccxt ib_insync solana web3 tqdm plotly openai stripe paypalrestsdk eth_account pyngrok")
    import streamlit as st
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import ccxt
    import plotly.express as px
    from ib_insync import *
    import nest_asyncio
    from web3 import Web3
    from sklearn.preprocessing import MinMaxScaler
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import LSTM, Dense, Dropout

# 🔧 Fix für den Event-Loop-Fehler
nest_asyncio.apply()

# 📌 Streamlit UI – Design wie Coinbase
st.set_page_config(page_title="KI-Trading Bot", layout="wide")
st.sidebar.title("🔍 KI-Trading Bot")
st.sidebar.markdown("🚀 **Automatisiertes Trading mit KI & DEX-APIs**")

# 📌 Benutzer-Input im UI
initial_balance = st.sidebar.number_input("Startkapital ($)", value=10000)
reinvest_ratio = st.sidebar.slider("Reinvestitionsrate (%)", min_value=0, max_value=100, value=50)
risk_per_trade = st.sidebar.slider("Max. Risiko pro Trade (%)", min_value=1, max_value=10, value=2)
take_profit = st.sidebar.slider("Take-Profit (%)", min_value=1, max_value=100, value=10)
stop_loss = st.sidebar.slider("Stop-Loss (%)", min_value=1, max_value=50, value=5)
strategy = st.sidebar.selectbox("KI-Trading-Strategie", ["Grid Trading", "AI Scalping", "Breakout-Trading"])

# 📌 Portfolio-Daten für Performance-Tracking
portfolio = {"Balance": initial_balance, "Trades": []}

# 📌 Verbindung zu Binance DEX
binance = ccxt.binance()

# 📌 AI-gestütztes Risikomanagement mit Reinvestition
def calculate_position_size(account_balance, risk_pct, stop_loss_pct, entry_price):
    reinvest_amount = account_balance * (reinvest_ratio / 100)
    risk_amount = (reinvest_amount * risk_pct) / 100
    stop_loss_amount = entry_price * (stop_loss_pct / 100)
    position_size = risk_amount / stop_loss_amount
    return max(position_size, 0.001)

# 📌 KI-Scalping mit Volatilitätsanalyse
def ai_scalping(crypto_pair):
    ticker = binance.fetch_ticker(crypto_pair)
    price = ticker['last']
    volatility = np.random.uniform(0.5, 2.0)
    if volatility > 1.5:
        place_crypto_order_with_tp_sl(crypto_pair, take_profit, stop_loss)
        return f"📈 AI Scalping Trade für {crypto_pair} gestartet! Preis: {price}"
    return "⚖️ Kein Scalping-Trade, Volatilität zu niedrig."

# 📌 Take-Profit/Stop-Loss für Krypto mit Reinvestition
def place_crypto_order_with_tp_sl(crypto_pair, tp_pct, sl_pct):
    ticker = binance.fetch_ticker(crypto_pair)
    entry_price = ticker['last']
    amount = calculate_position_size(portfolio["Balance"], risk_per_trade, sl_pct, entry_price)

    order = binance.create_market_buy_order(crypto_pair, amount)
    take_profit_price = entry_price * (1 + tp_pct / 100)
    stop_loss_price = entry_price * (1 - sl_pct / 100)

    portfolio["Trades"].append({"Asset": crypto_pair, "Entry": entry_price, "TP": take_profit_price, "SL": stop_loss_price})
    update_portfolio_balance(take_profit_price - entry_price)
    update_performance_chart()

    st.success(f"✅ Krypto-Trade für {crypto_pair} platziert! Menge: {amount:.5f}")
    st.info(f"🔒 Take-Profit: {take_profit_price:.2f}, Stop-Loss: {stop_loss_price:.2f}")

# 📌 Portfolio-Wachstum & Performance-Tracking
def update_portfolio_balance(profit):
    portfolio["Balance"] += profit * (reinvest_ratio / 100)

def update_performance_chart():
    df = pd.DataFrame(portfolio["Trades"])
    if not df.empty:
        df["Profit"] = df["TP"] - df["Entry"]
        fig = px.line(df, x=df.index, y="Profit", title="📊 Performance-Tracking: Gewinn/Verlust", labels={"Profit": "Gewinn ($)"})
        st.plotly_chart(fig)

# 📌 Dashboard mit Streamlit
st.title("🚀 KI-Trading Bot – Aktien & Krypto")
st.write(f"**🔍 Strategie:** {strategy}")

st.metric("📈 Portfolio-Balance ($)", f"{portfolio['Balance']:.2f}")

if st.button("📊 Starte KI-Trading"):
    if strategy == "AI Scalping":
        result = ai_scalping("BTC/USDT")
        st.write(result)

# 📌 Live-Performance-Charts
if st.sidebar.button("📊 Portfolio-Performance anzeigen"):
    update_performance_chart()

# 📌 Deployment Fix für Render.com
if __name__ == "__main__":
    os.system("pip install -r requirements.txt")
    os.system("streamlit run app.py")